Portfolio: deskstop version
blessing-michael/portfolio pull request #5
Opened 2023-06-09 14:39 UTC by blessing-michael

# Portfolio: Desktop version

In this project I;
- Used media queries to ensure the website displays correctly on desktop screens.
- Ensured there are [no linter errors](https://github.com/microverseinc/linters-config).
- Used CSS Grid and Flexbox to lay elements on the page.

2023-06-09 15:33 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @blessing-michael, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

- [ ] It is required to stick to the figma design as much as possible. kindly work on the alignment of the project information beside each of the project image. Tech lists of each project are not properly aligned. Kindly check the two screenshots below and work your design alongside the figma design.

### Your Design
![your-work-card](https://github.com/blessing-michael/portfolio/assets/26597432/f1271250-9bfc-4311-835c-0606aaecc8db)

### Figma Design
![figma-work-card](https://github.com/blessing-michael/portfolio/assets/26597432/f66b64be-42c6-4758-8df3-2a47d37795ac)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 23:00 UTC, AbdusSattar-70 reviewed
## Invalid CRR
Hi @blessing-michael , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that didn't pass all the linters, Please make sure to pass the linters before submitting the re-review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-10 08:13 UTC, roshan-bajgain requested changes
Hi @blessing-michael, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

 ## Required Changes ♻️
- [ ] I know everyone is facing the `webhint` problem. Hope it will as soon as possible.
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 08:13 UTC, roshan-bajgain commented on index.html
> +              <button class="tech-project-btn" type="submit">See project</button>
- [ ] You did great work but while make changes on previous reviewer you implement the wrong design. According to the project requirement the page is divided half of it contains the project's picture and the other half contains the project's description. Please see image below for reference.
- [ ] Please implement with all the cards.
### Figma design
![figma](https://github.com/blessing-michael/portfolio/assets/81727988/1c64d717-d4d7-404d-a50c-12b40574fac8)

### Your design
![his](https://github.com/blessing-michael/portfolio/assets/81727988/d31960f9-3176-484a-a65d-567b523e95f9)

2023-06-10 08:13 UTC, roshan-bajgain commented on index.html
> +              <button class="tech-project-btn" type="submit">See project</button>
- [ ] [Optional] I would suggest you please implement the active, hover and pressed effect on you buttons it make good user experience. Please implement with all the buttons
### Design
![his](https://github.com/blessing-michael/portfolio/assets/81727988/9eb0038e-e750-452c-9bc8-34b91935316d)

2023-06-10 09:39 UTC, Alusp approved these changes
Hi @blessing-michael, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![close](https://media.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif)

## Highlights

- [ ] Good Commit History :green_circle: 
- [ ] Good Github Flow :green_circle: 
- [ ] Good PR Summary :green_circle: 
- [ ] No Linter Errors :green_circle: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 10:25 UTC, merged